apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: goserver
spec:
  replicas: 4
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        image: herisson/goserver:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 3000
