apiVersion: v1
kind: Service
metadata:
  name: goserver-service
  labels:
    app: goserver-service
spec:
  selector:
    app: goserver-deployment
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
